import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations object
const translations = {
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.news': 'ニュース',
    'nav.fleet': 'バス紹介',
    'home.hero.fleet_button': 'バス紹介',
    'nav.pricing': '料金',
    'nav.process': 'ご利用の流れ',
    'nav.company': '会社概要',
    'nav.faq': 'よくある質問',
    'nav.careers': '採用情報',
    'nav.corporate': '法人向け',
    'nav.contact': 'お問い合わせ',
    'nav.quote': '見積もり',
    'nav.safety': '安全への取組み',
    'nav.terms': '運送約款',
    'nav.privacy': 'プライバシー',
    'nav.more': 'その他',
    
    // Company info
    'company.name': '大爽観光バス',
    'company.slogan1': '快適な旅と笑顔いっぱいの対応を常に心がけてまいります。',
    'company.slogan2': 'すべては、笑顔のために。',
    'company.slogan3': '「安心・丁寧・誠実」を心を込めてお届けします。',
    
    // Hero section
    'hero.title': 'すべては笑顔のために',
    'hero.subtitle': '大爽観光バス',
    'hero.description': 'お客様のニーズに合わせた最適な車種および旅程プランを提案し、今まで他社に実現ができなかった最大限に柔軟な対応を目指して行きます。',
    'hero.cta': 'お問い合わせ',
    
    // Services  
    'services.title': 'サービス紹介',
    'usage.title': '利用シーンの紹介',
    'services.airport': '空港送迎',
    'services.airport.description': '成田空港・羽田空港などホテルの送迎',
    'services.inbound': 'インバウンド旅行',
    'services.inbound.description': '外国人観光客のツアー利用',
    'services.daytrip': '日帰り旅行',
    'services.daytrip.description': '社員旅行・団体旅行利用',
    'services.ceremony': '冠婚葬祭',
    'services.ceremony.description': '婚式や法事などの送迎利用',
    'services.event': '合宿、イベント、展示会',
    'services.event.description': 'クラブ活動やイベント展示会の送迎',
    'services.contract': '契約サービス',
    'services.contract.description': '年間や期間が長い貸切バス利用',
    
    // Fleet
    'fleet.title': '車両の紹介',
    'fleet.large': '大型バス',
    'fleet.large.seats': '正座45座席or49座席',
    'fleet.large.description': '団体旅行での移動や荷物が多いとき',
    'fleet.midsize': '中型バス',
    'fleet.midsize.seats': '正座27座席',
    'fleet.midsize.description': 'ゆったり前後スペース・トランク2基',
    'fleet.rosa': 'マイクロバス（ローザタイプ）',
    'fleet.rosa.seats': '正座19座席',
    'fleet.rosa.description': 'トランクが広く、荷物多い時も◎',
    'fleet.coaster': 'マイクロバス（コースター）',
    'fleet.coaster.seats': '正座18座席',
    'fleet.coaster.description': 'スタイリッシュのボディにビジネス向き',
    'fleet.vip': 'マイクロバス（VIP仕様）',
    'fleet.vip.seats': '正座12座席',
    'fleet.vip.description': 'リクライニングシートでVIP感の演出',
    'fleet.commuter': 'コミューター',
    'fleet.commuter.seats': '正座13座席',
    'fleet.commuter.description': '予算が限られたとき小グループに最適',
    
    // Fleet - Detailed descriptions for Fleet page
    'fleet.large.description.detail': '貸切バスの中で最も大きいサイズ',
    'fleet.midsize.description.detail': 'ゆったり前後スペース・トランク2基',
    'fleet.rosa.description.detail': 'マイクロバスの中一番トランクの大きい',
    'fleet.coaster.description.detail': 'スタイリッシュのボディにビジネス向き',
    'fleet.vip.description.detail': 'マイクロバスの中一番トランクの大きい',
    'fleet.commuter.description.detail': '小旅行に最適',
    
    // Contact
    'contact.title': 'お問い合わせ',
    'contact.response': '2営業日以内にご返信いたします。',
    'contact.urgent': 'お急ぎの方は TEL 080-6588-4932（澤村）へ。',
    'contact.name': 'お名前',
    'contact.company': '会社名',
    'contact.email': 'メールアドレス',
    'contact.phone': '電話番号',
    'contact.message': 'お問い合わせ内容',
    'contact.submit': '送信',
    
    // Footer
    'footer.company': '大爽合同会社',
    'footer.address': '〒270-1102 千葉県我孫子市都12-31',
    'footer.phone': '+81-471-61-2355',
    'footer.email': 'c.sawamura55@gmail.com',
    
    // News Detail
    'news.share.copied': 'URLをコピーしました',
    'news.notfound.title': 'ニュースが見つかりません',
    'news.notfound.description': '指定されたニュース記事が存在しないか、削除された可能性があります。',
    'news.notfound.back': 'ニュース一覧に戻る',
    'news.breadcrumb.home': 'ホーム',
    'news.readtime': '読了時間約3分',
    'news.author': '大爽観光バス',
    'news.share': '共有',
    'news.footer.title': '他のニュースもチェック',
    'news.footer.description': '大爽観光バスの最新情報をお見逃しなく！',
    'news.footer.back': 'ニュース一覧に戻る',
    'news.footer.pricing.title': '大爽観光バスを利用したい方へ',
    
    // News Page
    'news.loading': '読み込み中...',
    'news.error.title': 'ニュースの取得に失敗しました',
    'news.error.description': 'インターネット接続を確認していただくか、しばらく時間をおいてから再度お試しください。',
    'news.error.retry': '再読み込み',
    'news.error.back.home': 'ホームに戻る',
    'news.error.persist': '問題が続く場合は、お気軽にお問い合わせください。',
    'news.error.contact': 'お問い合わせ',
    'news.error.phone': '電話: 03-1234-5678',
    'news.page.description': '大爽観光バスの最新情報をお届けします',
    'news.featured': '注目のニュース',
    'news.read.more': '詳しく見る',
    'news.no.results': '該当するニュースがありません。',
    'news.newsletter.title': '最新情報をお届け',
    'news.newsletter.description': '大爽観光バスの最新ニュースやお得な情報を、メールマガジンでお届けします。ご登録いただいた方には、特別割引クーポンをプレゼント！',
    'news.newsletter.placeholder': 'メールアドレスを入力',
    'news.newsletter.subscribe': '登録する',
    
    // FloatingContactButton
    'float.call': '電話する',
    
    // Footer
    'footer.services.title': 'サービス',
    'footer.about.title': '会社情報',
    'footer.contact.title': 'お問い合わせ',
    'footer.contact.form': 'お問い合わせフォーム',
    'footer.quote.free': '無料お見積もり',
    
    // Home Page Services
    'services.charter.description': '快適な貸切バスサービス',
    'services.guide.description': '観光地のご案内とプラン作成',
    'services.rental.description': '各種レンタカーサービス',
    'services.gym.description': 'フィットネスジム運営',
    
    // Company Page
    'company.ceo.title': '代表からのメッセージ',
    'company.ceo.message1': '大爽合同会社は2019年の設立以来、「{slogan}」をモットーに、お客様に寄り添ったサービスを提供してまいりました。',
    'company.ceo.message2': '私たちは単なる移動手段の提供ではなく、お客様の大切な時間と思い出作りを全力でサポートいたします。安全・安心を第一に、心のこもったおもてなしで皆様をお迎えいたします。',
    'company.ceo.message3': '今後も地域の皆様、そして日本を訪れる海外からのお客様に愛される会社として、成長を続けてまいります。',
    'company.ceo.name': '代表 澤村千凡',
    
    // Company Basic Info
    'company.basic.title': '会社概要',
    'company.basic.name': '会社名',
    'company.basic.name.value': '大爽合同会社（DAISOU LLC）',
    'company.basic.representative': '代表者',
    'company.basic.representative.value': '澤村千凡（Chiho Sawamura）',
    'company.basic.established': '設立',
    'company.basic.established.value': '2019年4月',
    'company.basic.address': '所在地',
    'company.basic.address.value': '〒270-1102 千葉県我孫子市都12-31',
    'company.basic.phone': '電話番号',
    'company.basic.email': 'メール',
    'company.basic.website': 'ウェブサイト',
    
    // Company Services
    'company.services.title': '事業内容',
    'company.services.charter': '貸切バス事業',
    'company.services.charter.desc': '観光・送迎・冠婚葬祭等の貸切バスサービス',
    'company.services.guide': '観光案内事業',
    'company.services.guide.desc': '旅行プラン作成・観光地案内・通訳サービス',
    'company.services.rental': '通訳 ガイド手配事業',
    'company.services.rental.desc': '必要な言語に応じて手配',
    'company.services.gym': 'バス車内広告事業',
    'company.services.gym.desc': '観光バス×広告の運営',
    
    // Company Licenses
    'company.licenses.title': '許可・認可',
    'company.licenses.charter.type': '一般貸切旅客自動車運送事業',
    'company.licenses.charter.number': '関東自一第 952 号',
    'company.licenses.charter.authority': '関東運輸局',
    'company.licenses.rental.type': 'レンタカー事業',
    'company.licenses.rental.number': '千葉運輸第 58 号',
    'company.licenses.rental.authority': '千葉運輸支局',
    'company.licenses.travel.type': '旅行業',
    'company.licenses.travel.number': '千葉第 69 号',
    'company.licenses.travel.authority': '千葉県',
    
    // Company History
    'company.history.title': '沿革',
    'company.history.2019.year': '2019年4月',
    'company.history.2019.event': '大爽合同会社設立',
    'company.history.2019.desc': '一般貸切旅客自動車運送事業を開始',
    'company.history.2020.year': '2020年',
    'company.history.2020.event': 'サービス拡充',
    'company.history.2020.desc': '観光案内・プラン作成サービスを追加',
    'company.history.2021.year': '2021年',
    'company.history.2021.event': '車両増車',
    'company.history.2021.desc': 'マイクロバス2台目導入',
    'company.history.2022.year': '2022年',
    'company.history.2022.event': '中型バス導入',
    'company.history.2022.desc': '27座席中型バスでサービス範囲拡大',
    'company.history.2023.year': '2023年',
    'company.history.2023.event': 'インバウンド強化',
    'company.history.2023.desc': '多言語対応とVIP送迎サービス開始',
    
    // Company Banking
    'company.banking.title': '取引銀行',
    'company.banking.mizuho': 'みずほ銀行',
    'company.banking.chiba': '千葉銀行',
    
    // Company Location
    'company.location.title': 'アクセス',
    'company.location.address.label': '住所',
    'company.location.station.label': '最寄り駅',
    'company.location.station.value': 'JR成田線「布佐駅」より徒歩10分',
    'company.location.access.label': 'アクセス',
    'company.location.access.value': '成田空港より車で約45分\n東京都心より車で約1時間',
    
    // Home Page CTA
    'home.cta.title': 'お気軽にお問い合わせください',
    
    // Home Page Fleet Section
    'home.fleet.description': '多様なニーズにお応えする充実の車両ラインナップ',
    'home.fleet.seats.27': '27座席',
    'home.fleet.seats.coaster': '18正座 + 5補助',
    'home.fleet.seats.rosa': '19正座 + 5補助',
    'home.fleet.name.coaster': 'マイクロバス (Coaster)',
    'home.fleet.name.rosa': 'マイクロバス (Rosa)',
    'home.fleet.view.details': '詳しく見る',
    'home.company.since': '2019年設立',
    
    // Fleet Page
    'fleet.page.description': 'お客様のニーズに合わせて選べる、安全で快適な車両をご用意しております。すべての車両で定期的な安全点検と清掃を実施し、快適な旅をサポートいたします。',
    'fleet.features.title': '主な特徴',
    'fleet.specs.title': '車両仕様',
    'fleet.specs.length': '全長',
    'fleet.specs.width': '全幅', 
    'fleet.specs.height': '全高',
    'fleet.specs.capacity': '定員',
    
    // Fleet Vehicle Features
    'fleet.large.name.en': 'Large-sized bus',
    'fleet.large.feature1': '大人数のご利用',
    'fleet.large.feature2': 'DVD、マイク、冷蔵庫完備',
    'fleet.large.feature3': '大容量トランク3基',
    'fleet.large.feature4': 'サロンタイプ',
    'fleet.large.length': '約12m',
    'fleet.large.width': '約2.5m',
    'fleet.large.height': '約3.5～3.8m',
    'fleet.large.capacity': '45名～49名（正座席）',
    
    'fleet.midsize.name.en': 'Mid-size Coach',
    'fleet.midsize.feature1': 'ゆったりとした座席間隔',
    'fleet.midsize.feature2': '大容量トランク2基',
    'fleet.midsize.feature3': 'エアコン完備',
    'fleet.midsize.feature4': 'リクライニングシート',
    'fleet.midsize.length': '約9m',
    'fleet.midsize.width': '約2.3m',
    'fleet.midsize.height': '約3.2m',
    'fleet.midsize.capacity': '27名（正座席）',
    

    'fleet.coaster.name': 'マイクロバス (Coaster)',
    'fleet.coaster.name.en': 'Microbus Coaster',
    'fleet.coaster.feature1': '小回りの利く機動性',
    'fleet.coaster.feature2': 'コンパクトながら快適',
    'fleet.coaster.feature3': '落ち着いたシルバー色が高級感や清潔感を演出',
    'fleet.coaster.feature4': '少人数グループに最適',
    'fleet.coaster.length': '約7m',
    'fleet.coaster.width': '約2.0m',
    'fleet.coaster.height': '約2.6m',
    'fleet.coaster.capacity': '23名（正座18+補助5）',
    

    'fleet.rosa.name': 'マイクロバス (ローザタイプ)',
    'fleet.rosa.name.en': 'Micro bus Superlong type',
    'fleet.rosa.feature1': '大容量トランク',
    'fleet.rosa.feature2': 'ゴルフツアーや荷物の多いに最適',
    'fleet.rosa.feature3': 'マイク完備',
    'fleet.rosa.feature4': '快適な乗り心地',
    'fleet.rosa.length': '約7.8m',
    'fleet.rosa.width': '約2.0m',
    'fleet.rosa.height': '約2.6m',
    'fleet.rosa.capacity': '19名（正座19+補助5）',
    
    'fleet.vip.name': 'マイクロバス (VIP仕様)',
    'fleet.vip.name.en': 'Microbus VIP Specification',
    'fleet.vip.feature1': '希少車両',
    'fleet.vip.feature2': 'リクライニングシート',
    'fleet.vip.feature3': '観音扉トランク',
    'fleet.vip.feature4': 'マイク、冷蔵庫完備',
    'fleet.vip.length': '約7.8m',
    'fleet.vip.width': '約2.0m',
    'fleet.vip.height': '約2.6m',
    'fleet.vip.capacity': '12名（補助なし）',
    
    'fleet.commuter.name': 'コミューター',
    'fleet.commuter.name.en': '14seat Hiace',
    'fleet.commuter.feature1': '小回りが利く',
    'fleet.commuter.feature2': '少人数の観光におすすめ',
    'fleet.commuter.feature3': '最後尾のシートを畳むことで',
    'fleet.commuter.feature4': 'スーツケースの積み込みが可能',
    'fleet.commuter.length': '約5m',
    'fleet.commuter.width': '約1.9m',
    'fleet.commuter.height': '約2.3m',
    'fleet.commuter.capacity': '13名（最後尾シートを畳む場合は9名）',
    
    // Fleet Safety Section
    'fleet.safety.title': '安全への取り組み',
    'fleet.safety.description': 'すべての車両に最新の安全装備を搭載し、定期的な点検・整備を実施しています。',
    'fleet.safety.equipment.title': '安全装備',
    'fleet.safety.equipment.description': 'ABS、エアバッグ、シートベルトなど最新の安全装備を完備',
    'fleet.safety.training.title': '運転者教育',
    'fleet.safety.training.description': '定期的な安全講習と技能向上研修を実施',
    'fleet.safety.inspection.title': '車両点検',
    'fleet.safety.inspection.description': '法定点検に加え、独自の安全チェックを実施',
    
    // Fleet CTA
    'fleet.cta.title': '車両のご予約・お問い合わせ',
    'fleet.cta.description': 'ご利用人数や目的に応じて最適な車両をご提案いたします。お気軽にお問い合わせください。',
    'fleet.cta.contact': 'お問い合わせ',
    'fleet.cta.quote': '見積もり依頼',
    
    // Contact Page Details
    'contact.info.title': 'お問い合わせ先',
    'contact.info.phone': '電話番号',
    'contact.info.mobile': '携帯: 080-6588-4932（澤村）',
    'contact.info.email': 'メール',
    'contact.info.address': '住所',
    'contact.info.address.detail': '〒270-1102\n千葉県我孫子市都12-31',
    
    // Contact Page Extended
    'contact.hours': '営業時間',
    'contact.hours.detail': '平日 9:00-17:00\n土日祝 応相談',
    'contact.sns': 'SNS',
    'contact.form.title': 'お問い合わせフォーム',
    'contact.form.type.general': '一般問い合わせ',
    'contact.form.type.group': '団体予約',
    'contact.form.type.corporate': '法人専用',
    'contact.form.date': 'ご利用予定日',
    'contact.form.participants': '参加人数',
    'contact.form.destination': '目的地・ルート',
    'contact.form.destination.placeholder': '例：成田空港 → 東京スカイツリー → ホテル',
    'contact.form.placeholder.general': 'ご質問やご要望をお聞かせください',
    'contact.form.placeholder.group': 'ご利用目的、詳細なスケジュール、特別なご要望などをお聞かせください',
    'contact.form.placeholder.corporate': '法人向けサービスに関するお問い合わせ内容をお聞かせください',
    'contact.form.submitting': '送信中...',
    'contact.form.success': 'お問い合わせありがとうございます。2営業日以内にご返信いたします。',
    'contact.form.error': '申し訳ありません、送信に失敗しました。時間をおいて再度お試しください。',
    'contact.emergency.title': '緊急時・お急ぎの場合',
    'contact.emergency.description': '当日の緊急連絡や至急のご相談は、直接お電話ください。',
    'contact.emergency.call': '080-6588-4932（澤村）に電話する',
    
    // Safety Page
    'safety.description': 'お客様の安全・安心を最優先に、徹底した安全管理を実施しています。',
    'safety.policy.title': '安全方針',
    'safety.policy.subtitle': '私たちは以下の方針に基づき、安全輸送を実現します',
    'safety.policy.management.title': '経営方針',
    'safety.policy.management.desc': '輸送の安全を事業の根幹と位置づけ、明確な目標と計画を策定。',
    'safety.policy.priority.title': '安全第一',
    'safety.policy.priority.desc': '全従業員が「人命最優先・安全第一」を徹底。',
    'safety.policy.compliance.title': '法規遵守',
    'safety.policy.compliance.desc': '交通法規遵守と環境保護を両立し、継続的に改善。',
    'safety.policy.disclosure.title': '情報公開',
    'safety.policy.disclosure.desc': '安全に関する情報は社内外へ積極的に公開。',
    
    'safety.measures.title': '具体的な安全対策',
    'safety.measures.subtitle': '車両・人・システムの三方面から安全を確保します',
    'safety.measures.vehicle.title': '車両安全装備',
    'safety.measures.vehicle.abs': 'ABS（アンチロックブレーキシステム）',
    'safety.measures.vehicle.airbag': 'エアバッグシステム',
    'safety.measures.vehicle.seatbelt': 'シートベルト（全席）',
    'safety.measures.vehicle.camera': 'バックカメラ・ドライブレコーダー',
    'safety.measures.vehicle.emergency': '非常口・非常灯',
    'safety.measures.vehicle.safety': '消火器・救急箱',
    'safety.measures.training.title': '運転者教育',
    'safety.measures.training.orientation': '入社時安全研修',
    'safety.measures.training.regular': '定期安全講習会',
    'safety.measures.training.prediction': '危険予知訓練',
    'safety.measures.training.health': '健康管理指導',
    'safety.measures.training.aptitude': '適性診断受診',
    'safety.measures.training.eco': 'エコドライブ講習',
    'safety.measures.maintenance.title': '車両点検・整備',
    'safety.measures.maintenance.daily': '日常点検（運行前後）',
    'safety.measures.maintenance.regular': '定期点検（法定点検）',
    'safety.measures.maintenance.cleaning': '車両清掃・消毒',
    'safety.measures.maintenance.parts': 'タイヤ・ブレーキ点検',
    'safety.measures.maintenance.record': '整備記録管理',
    'safety.measures.maintenance.response': '不具合時即座対応',
    
    'safety.training.title': '運転者研修制度',
    'safety.training.description1': 'すべての運転者に対して、入社時研修から継続的な安全教育まで、体系的な研修プログラムを実施しています。',
    'safety.training.description2': '安全運転技術の向上はもちろん、接客マナーや緊急時対応まで、お客様に安心してご利用いただくための総合的な教育を行っています。',
    'safety.training.orientation.title': '入社時研修',
    'safety.training.orientation.desc': '40時間の集中研修',
    'safety.training.regular.title': '定期研修',
    'safety.training.regular.desc': '月1回の安全講習',
    'safety.training.aptitude.title': '適性診断',
    'safety.training.aptitude.desc': '年1回の受診義務',
    'safety.training.health.title': '健康管理',
    'safety.training.health.desc': '定期健康診断',
    'safety.training.image.alt': '運転者研修',
    
    'safety.covid.title': '感染症対策',
    'safety.covid.subtitle': '新型コロナウイルス感染症対策を徹底し、安心してご利用いただけます',
    'safety.covid.vehicle.title': '車両内の感染症対策',
    'safety.covid.vehicle.disinfection': '運行前後の車両内消毒',
    'safety.covid.vehicle.cleaning': '座席・手すり等の清拭',
    'safety.covid.vehicle.ventilation': '換気システムの活用',
    'safety.covid.vehicle.capacity': '乗車人数の調整',
    'safety.covid.vehicle.spacing': '座席間隔の確保',
    'safety.covid.staff.title': '乗務員の健康管理',
    'safety.covid.staff.temperature': '毎日の体温測定',
    'safety.covid.staff.mask': 'マスク着用の徹底',
    'safety.covid.staff.sanitizer': '手指消毒の実施',
    'safety.covid.staff.absence': '体調不良時の乗務禁止',
    'safety.covid.staff.testing': '定期的なPCR検査',
    'safety.covid.customer.title': 'お客様へのお願い',
    'safety.covid.customer.mask': 'マスク着用のお願い',
    'safety.covid.customer.sanitizer': '手指消毒のご協力',
    'safety.covid.customer.health': '体調不良時のご相談',
    'safety.covid.customer.seating': '座席指定のご協力',
    'safety.covid.customer.conversation': '車内での会話を控えめに',
    
    'safety.emergency.title': '緊急時の連絡先',
    'safety.emergency.description': '運行中に何らかの異常を感じられた場合は、immediately にご連絡ください。',
    'safety.emergency.contact': '緊急連絡先: 080-6588-4932',
    'safety.emergency.police': '警察: 110番',
    
    'safety.record.title': '安全実績',
    'safety.record.accidents.number': '0件',
    'safety.record.accidents.label': '重大事故件数',
    'safety.record.accidents.period': '（2019年〜現在）',
    'safety.record.inspection.number': '100%',
    'safety.record.inspection.label': '法定点検実施率',
    'safety.record.inspection.period': '（毎年）',
    'safety.record.training.number': '月1回',
    'safety.record.training.label': '安全講習実施',
    'safety.record.training.period': '（全運転者対象）',
    
    // FAQ Page
    'faq.description': 'よくある質問を簡潔にまとめました。お探しの情報が見つからない場合は、お気軽にお問い合わせください。',
    'faq.search.placeholder': 'キーワードで検索...',
    
    // FAQ Categories
    'faq.category.all': 'すべて',
    'faq.category.booking': '予約について',
    'faq.category.pricing': '料金について',
    'faq.category.safety': '安全について',
    'faq.category.service': 'サービスについて',
    'faq.category.vehicle': '車両について',
    'faq.category.other': 'その他',
    
    // FAQ Questions & Answers
    'faq.q1': '予約はいつまでに行えばよいですか？',
    'faq.a1': 'ご利用希望日の3日前までにご予約をお願いいたします。ただし、繁忙期（ゴールデンウィーク、お盆、年末年始等）は1週間前までの予約をお勧めします。お急ぎの場合は直接お電話でご相談ください。',
    'faq.q2': 'キャンセルはできますか？',
    'faq.a2': 'はい、キャンセル可能です。ただし、キャンセル料が発生する場合があります。ご利用日の7日前まで：無料、3-6日前：料金の30%、前日・当日：料金の100%となります。詳細は運送約款をご確認ください。',
    'faq.q3': '料金はどのように決まりますか？',
    'faq.a3': '基本料金は車両サイズ、ご利用時間、走行距離によって決まります。平日・土日祝日、季節による料金変動があります。お見積もりは無料ですので、お気軽にお問い合わせください。',
    'faq.q4': '追加料金はかかりますか？',
    'faq.a4': '基本料金に含まれない場合の追加料金として、高速道路料金、駐車場料金、宿泊を伴う場合の運転者宿泊費等があります。事前にお見積もりでご確認いただけます。',
    'faq.q5': '運転者の安全対策はどうなっていますか？',
    'faq.a5': '全運転者に対して定期的な安全講習、適性診断、健康管理を実施しています。また、運行前の体調確認、アルコールチェックを徹底し、安全運転を心がけています。',
    'faq.q6': '車両の安全装備はどうなっていますか？',
    'faq.a6': '全車両にABS、エアバッグ、ドライブレコーダー、バックカメラを装備しています。また、定期点検・整備を法定基準以上に実施し、安全性を確保しています。',
    'faq.q7': '英語での対応は可能ですか？',
    'faq.a7': 'はい、可能です。日本語・英語のバイリンガル対応で、海外からのお客様にも安心してご利用いただけます。観光案内や通訳サービスも承っております。',
    'faq.q8': '観光プランの提案はしてもらえますか？',
    'faq.a8': 'はい、承っております。お客様のご希望や予算に応じて、最適な観光ルートをご提案いたします。宿泊施設や観光施設のチケット手配も可能です。',
    'faq.q9': '何人まで乗車できますか？',
    'faq.a9': '中型バス：27名、マイクロバス（Coaster）：23名（正座18+補助5）、マイクロバス（Rosa）：24名（正座19+補助5）となっております。詳細は車両紹介ページをご覧ください。',
    'faq.q10': '荷物はどの程度積めますか？',
    'faq.a10': '各車両にトランクスペースがございます。中型バスは大容量トランク2基、マイクロバス（Rosa）は大型トランクを装備しており、スーツケースや大きな荷物も安心です。',
    'faq.q11': '成田空港以外での送迎も可能ですか？',
    'faq.a11': 'はい、可能です。羽田空港、各駅、ホテル等、ご希望の場所での送迎を承っております。関東一円が基本エリアですが、東北・関西方面もご相談に応じます。',
    'faq.q12': '感染症対策はどうなっていますか？',
    'faq.a12': '車両の消毒・清掃、換気の徹底、運転者の健康管理、マスク着用等、新型コロナウイルス感染症対策を実施しています。詳細は安全への取り組みページをご覧ください。',
    
    // FAQ UI Elements
    'faq.no.results': '該当する質問が見つかりません。',
    'faq.reset.search': '検索条件をリセット',
    'faq.contact.title': 'お探しの情報が見つかりませんか？',
    'faq.contact.description': 'お気軽にお問い合わせください。専門スタッフが丁寧にお答えいたします。',
    'faq.contact.phone.title': 'お電話でのお問い合わせ',
    'faq.contact.phone.hours': '平日 9:00-17:00\n土日祝 応相談',
    'faq.contact.email.title': 'メールでのお問い合わせ',
    'faq.contact.email.hours': '2営業日以内にご返信\n24時間受付中',
    'faq.contact.form': 'お問い合わせフォーム',
    'faq.popular.title': '人気の質問',
    'faq.view.details': '詳しく見る',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.news': 'News',
    'nav.fleet': 'Fleet',
    // Home Hero button label (separate from nav)
    'home.hero.fleet_button': 'Fleet Type of bus',
    'nav.pricing': 'Pricing',
    'nav.process': 'Process',
    'nav.company': 'Company',
    'nav.faq': 'FAQ',
    'nav.careers': 'Careers',
    'nav.corporate': 'Corporate',
    'nav.contact': 'Contact',
    'nav.quote': 'Quote',
    'nav.safety': 'Safety',
    'nav.terms': 'Terms',
    'nav.privacy': 'Privacy',
    'nav.more': 'More',
    
    // Company info
    'company.name': 'DAISOU Travel Bus',
    'company.slogan1': 'Comfortable journeys delivered with genuine smiles.',
    'company.slogan2': 'All for Smiles.',
    'company.slogan3': 'Safety, Care and Integrity—every mile, every time.',
    
    // Hero section
    'hero.title': 'All for Smiles',
    'hero.subtitle': 'DAISOU TRAVEL  BUS',
    'hero.description': 'We design the perfect combinationof vehicles and travel plans to matcheach customer’s needs. With a commitment to flexibility beyond what other companies can offer, we strive to make every journey uniquely comfortable and memorable.',
    'hero.cta': 'Contact Us',
    
    // Services
    'services.title': 'Our Services',
    'usage.title': 'Usage Scenarios',
    'services.airport': 'Airport Transfer',
    'services.airport.description': 'Transfer services from Narita airports and Haneda airports',
    'services.inbound': 'Inbound Tourism',
    'services.inbound.description': 'Tour services for international tourists',
    'services.daytrip': 'Day Trips',
    'services.daytrip.description': 'Corporate and group travel services',
    'services.ceremony': 'Ceremonial Events',
    'services.ceremony.description': 'Transportation for weddings and memorial services',
    'services.event': 'Training Camps & Events',
    'services.event.description': 'Transport for club activities, events and exhibitions',
    'services.contract': 'Contract Services',
    'services.contract.description': 'Long-term and annual charter bus services',
    
    // Fleet
    'fleet.title': 'Our Fleet',
    'fleet.large': 'Large Bus',
    'fleet.large.seats': '45 or 49 Regular Seats',
    'fleet.large.description': 'Ideal for group travel and when you have lots of luggage',
    'fleet.midsize': 'Mid-size Coach',
    'fleet.midsize.seats': '27 Regular Seats',
    'fleet.midsize.description': 'Spacious legroom and dual trunk compartments',
    'fleet.rosa': 'Microbus (Rosa Type)',
    'fleet.rosa.seats': '19 Regular Seats',
    'fleet.rosa.description': 'Spacious trunk, perfect even with lots of baggage',
    'fleet.coaster': 'Microbus (Coaster)',
    'fleet.coaster.seats': '18 Regular Seats',
    'fleet.coaster.description': 'Stylish body design, business-oriented',
    'fleet.vip': 'Microbus (VIP Specification)',
    'fleet.vip.seats': '12 Regular Seats',
    'fleet.vip.description': 'Reclining seats for a VIP experience',
    'fleet.commuter': 'Commuter',
    'fleet.commuter.seats': '13 Regular Seats',
    'fleet.commuter.description': 'Perfect for small groups on a limited budget',
    
    // Fleet - Detailed descriptions for Fleet page
    'fleet.large.description.detail': 'The largest size among charter buses',
    'fleet.midsize.description.detail': 'Spacious legroom and dual trunk compartments',
    'fleet.rosa.description.detail': 'The largest trunk among microbuses',
    'fleet.coaster.description.detail': 'Stylish body design, business-oriented',
    'fleet.vip.description.detail': 'The largest trunk among microbuses',
    'fleet.commuter.description.detail': 'Perfect for small trips',
    
    // Contact
    'contact.title': 'Get In Touch with Us',
    'contact.response': 'We\'d love to hear from you. ',
    'contact.urgent': 'Whether you have a question about our services, pricing, or anything else, our team is ready to answer all your questions.',
    'contact.name': 'Name',
    'contact.company': 'Company',
    'contact.email': 'E-mail',
    'contact.phone': 'Phone',
    'contact.message': 'Inquiry',
    'contact.submit': 'Submit',
    
    // Footer
    'footer.company': 'DAISOU LLC',
    'footer.address': '〒270-1102 12-31 Miyako, Abiko-shi, Chiba',
    'footer.phone': '+81-471-61-2355',
    'footer.email': 'c.sawamura55@gmail.com',
    
    // News Detail
    'news.share.copied': 'URL copied to clipboard',
    'news.notfound.title': 'News Not Found',
    'news.notfound.description': 'The requested news article does not exist or may have been deleted.',
    'news.notfound.back': 'Back to News',
    'news.breadcrumb.home': 'Home',
    'news.readtime': 'About 3 min read',
    'news.author': 'Daisou Tourism Bus',
    'news.share': 'Share',
    'news.footer.title': 'Check Out Other News',
    'news.footer.description': "Don't miss the latest updates from Daisou Tourism Bus!",
    'news.footer.back': 'Back to News List',
    'news.footer.pricing.title': 'For Those Interested in Using Daisou Tourism Bus',
    
    // News Page
    'news.loading': 'Loading...',
    'news.error.title': 'Failed to Load News',
    'news.error.description': 'Please check your internet connection or try again later.',
    'news.error.retry': 'Retry',
    'news.error.back.home': 'Back to Home',
    'news.error.persist': 'If the problem persists, please feel free to contact us.',
    'news.error.contact': 'Contact Us',
    'news.error.phone': 'Phone: 03-1234-5678',
    'news.page.description': 'Latest updates from Daisou Tourism Bus',
    'news.featured': 'Featured News',
    'news.read.more': 'Read More',
    'news.no.results': 'No news found.',
    'news.newsletter.title': 'Latest Updates',
    'news.newsletter.description': 'Get the latest news and special offers from Daisou Tourism Bus delivered to your inbox. Subscribers receive a special discount coupon!',
    'news.newsletter.placeholder': 'Enter email address',
    'news.newsletter.subscribe': 'Subscribe',
    
    // FloatingContactButton
    'float.call': 'Call',
    
    // Footer
    'footer.services.title': 'Services',
    'footer.about.title': 'About Us',
    'footer.contact.title': 'Contact',
    'footer.contact.form': 'Contact Form',
    'footer.quote.free': 'Free Quote',
    
    // Home Page Services
    'services.charter.description': 'Comfortable charter bus service',
    'services.guide.description': 'Tourist guidance and planning',
    'services.rental.description': 'Various car rental services',
    'services.gym.description': 'Fitness gym management',
    
    // Company Page
    'company.ceo.title': 'Message from CEO',
    'company.ceo.message1': 'Since our establishment in 2019, Daisou LLC has been providing customer-focused services with the motto "{slogan}".',
    'company.ceo.message2': 'We do more than just provide transportation; we fully support our customers\' precious time and memory-making. Safety and security come first, and we welcome everyone with heartfelt hospitality.',
    'company.ceo.message3': 'We will continue to grow as a company loved by the local community and overseas visitors to Japan.',
    'company.ceo.name': 'CEO Chiho Sawamura',
    
    // Company Basic Info
    'company.basic.title': 'Company Overview',
    'company.basic.name': 'Company Name',
    'company.basic.name.value': 'DAISOU LLC',
    'company.basic.representative': 'Representative',
    'company.basic.representative.value': 'Chiho Sawamura',
    'company.basic.established': 'Established',
    'company.basic.established.value': 'April 2019',
    'company.basic.address': 'Address',
    'company.basic.address.value': '12-31 Miyako, Abiko-shi, Chiba 270-1102',
    'company.basic.phone': 'Phone',
    'company.basic.email': 'Email',
    'company.basic.website': 'Website',
    
    // Company Services
    'company.services.title': 'Business Services',
    'company.services.charter': 'Charter Bus Service',
    'company.services.charter.desc': 'Charter bus services for tourism, transfers, and special events',
    'company.services.guide': 'Tourism Guide Service',
    'company.services.guide.desc': 'Travel planning, tourist guidance, and interpretation services',
    'company.services.rental': 'Interpreter & Guide Arrangement Service',
    'company.services.rental.desc': 'Arrangement according to required languages',
    'company.services.gym': 'Bus In-vehicle Advertising Service',
    'company.services.gym.desc': 'Tourism bus × advertising management',
    
    // Company Licenses
    'company.licenses.title': 'Licenses & Permits',
    'company.licenses.charter.type': 'General Charter Passenger Transport',
    'company.licenses.charter.number': 'Kanto Transport No. 952',
    'company.licenses.charter.authority': 'Kanto Regional Transport Bureau',
    'company.licenses.rental.type': 'Car Rental Business',
    'company.licenses.rental.number': 'Chiba Transport No. 58',
    'company.licenses.rental.authority': 'Chiba Transport Branch',
    'company.licenses.travel.type': 'Travel Agency',
    'company.licenses.travel.number': 'Chiba No. 69',
    'company.licenses.travel.authority': 'Chiba Prefecture',
    
    // Company History
    'company.history.title': 'Company History',
    'company.history.2019.year': 'April 2019',
    'company.history.2019.event': 'DAISOU LLC Established',
    'company.history.2019.desc': 'Started general charter passenger transport business',
    'company.history.2020.year': '2020',
    'company.history.2020.event': 'Service Expansion',
    'company.history.2020.desc': 'Added tourism guidance and travel planning services',
    'company.history.2021.year': '2021',
    'company.history.2021.event': 'Fleet Expansion',
    'company.history.2021.desc': 'Introduced second microbus',
    'company.history.2022.year': '2022',
    'company.history.2022.event': 'Mid-size Bus Introduction',
    'company.history.2022.desc': 'Expanded service range with 27-seat mid-size bus',
    'company.history.2023.year': '2023',
    'company.history.2023.event': 'Inbound Tourism Enhancement',
    'company.history.2023.desc': 'Started multilingual support and VIP transfer services',
    
    // Company Banking
    'company.banking.title': 'Partner Banks',
    'company.banking.mizuho': 'Mizuho Bank',
    'company.banking.chiba': 'Chiba Bank',
    
    // Company Location
    'company.location.title': 'Access',
    'company.location.address.label': 'Address',
    'company.location.station.label': 'Nearest Station',
    'company.location.station.value': '10 minutes on foot from Fusa Station (JR Narita Line)',
    'company.location.access.label': 'Access',
    'company.location.access.value': '45 minutes by car from Narita Airport\n1 hour by car from Tokyo city center',
    
    // Home Page CTA
    'home.cta.title': 'Feel Free to Contact Us',
    
    // Home Page Fleet Section
    'home.fleet.description': 'A complete fleet lineup to meet diverse needs',
    'home.fleet.seats.27': '27 Seats',
    'home.fleet.seats.coaster': '18 Regular + 5 Auxiliary',
    'home.fleet.seats.rosa': '19 Regular + 5 Auxiliary',
    'home.fleet.name.coaster': 'Microbus (Coaster)',
    'home.fleet.name.rosa': 'Microbus (Rosa)',
    'home.fleet.view.details': 'View Details',
    'home.company.since': 'Since 2019',
    
    // Fleet Page
    'fleet.page.description': 'We provide safe and comfortable vehicles to choose from according to your needs. Regular safety inspections and cleaning are conducted on all vehicles to support comfortable travel.',
    'fleet.features.title': 'Key Features',
    'fleet.specs.title': 'Vehicle Specifications',
    'fleet.specs.length': 'Length',
    'fleet.specs.width': 'Width',
    'fleet.specs.height': 'Height',
    'fleet.specs.capacity': 'Capacity',
    
    // Fleet Vehicle Features
    'fleet.large.name.en': 'Large-sized bus',
    'fleet.large.feature1': 'For large groups',
    'fleet.large.feature2': 'Equipped with DVD, microphone, refrigerator',
    'fleet.large.feature3': 'Large-capacity trunk (3 compartments)',
    'fleet.large.feature4': 'Salon-type seating',
    'fleet.large.length': 'Approx. 12m',
    'fleet.large.width': 'Approx. 2.5m',
    'fleet.large.height': 'Approx. 3.5-3.8m',
    'fleet.large.capacity': '45-49 passengers (regular seats)',
    
    'fleet.midsize.name.en': 'Mid-size Coach',
    'fleet.midsize.feature1': 'Spacious seat spacing',
    'fleet.midsize.feature2': 'Dual large-capacity trunks',
    'fleet.midsize.feature3': 'Full air conditioning',
    'fleet.midsize.feature4': 'Reclining seats',
    'fleet.midsize.length': 'Approx. 9m',
    'fleet.midsize.width': 'Approx. 2.3m',
    'fleet.midsize.height': 'Approx. 3.2m',
    'fleet.midsize.capacity': '27 passengers (regular seats)',
    
    'fleet.coaster.name': 'Microbus (Coaster)',
    'fleet.coaster.name.en': 'Microbus Coaster',
    'fleet.coaster.feature1': 'Excellent maneuverability',
    'fleet.coaster.feature2': 'Compact yet comfortable',
    'fleet.coaster.feature3': 'Calm silver color creates a sense of luxury and cleanliness',
    'fleet.coaster.feature4': 'Perfect for small groups',
    'fleet.coaster.length': 'Approx. 7m',
    'fleet.coaster.width': 'Approx. 2.0m',
    'fleet.coaster.height': 'Approx. 2.6m',
    'fleet.coaster.capacity': '23 passengers (18 regular + 5 auxiliary)',
    

    'fleet.rosa.name': 'Microbus (Rosa Type)',
    'fleet.rosa.name.en': 'Micro bus Superlong type',
    'fleet.rosa.feature1': 'Large-capacity trunk',
    'fleet.rosa.feature2': 'Perfect for golf tours and heavy luggage',
    'fleet.rosa.feature3': 'Microphone equipped',
    'fleet.rosa.feature4': 'Comfortable ride',
    'fleet.rosa.length': 'Approx. 7.8m',
    'fleet.rosa.width': 'Approx. 2.0m',
    'fleet.rosa.height': 'Approx. 2.6m',
    'fleet.rosa.capacity': '19 passengers (19 regular + 5 auxiliary)',
    
    'fleet.vip.name': 'Microbus (VIP Specification)',
    'fleet.vip.name.en': 'Microbus VIP Specification',
    'fleet.vip.feature1': 'Rare vehicle',
    'fleet.vip.feature2': 'Reclining seats',
    'fleet.vip.feature3': 'Double-door trunk',
    'fleet.vip.feature4': 'Microphone and refrigerator equipped',
    'fleet.vip.length': 'Approx. 7.8m',
    'fleet.vip.width': 'Approx. 2.0m',
    'fleet.vip.height': 'Approx. 2.6m',
    'fleet.vip.capacity': '12 passengers (no auxiliary seats)',
    
    'fleet.commuter.name': 'Commuter',
    'fleet.commuter.name.en': '14seat Hiace',
    'fleet.commuter.feature1': 'Excellent maneuverability',
    'fleet.commuter.feature2': 'Recommended for small group sightseeing',
    'fleet.commuter.feature3': 'By folding the rear seats',
    'fleet.commuter.feature4': 'Suitcase loading is possible',
    'fleet.commuter.length': 'Approx. 5m',
    'fleet.commuter.width': 'Approx. 1.9m',
    'fleet.commuter.height': 'Approx. 2.3m',
    'fleet.commuter.capacity': '13 passengers (9 passengers when rear seats folded)',
    
    // Fleet Safety Section
    'fleet.safety.title': 'Our Safety Commitment',
    'fleet.safety.description': 'All vehicles are equipped with the latest safety features and undergo regular inspections and maintenance.',
    'fleet.safety.equipment.title': 'Safety Equipment',
    'fleet.safety.equipment.description': 'Fully equipped with latest safety features including ABS, airbags, and seatbelts',
    'fleet.safety.training.title': 'Driver Training',
    'fleet.safety.training.description': 'Regular safety training and skill improvement programs',
    'fleet.safety.inspection.title': 'Vehicle Inspection',
    'fleet.safety.inspection.description': 'Our own safety checks in addition to mandatory inspections',
    
    // Fleet CTA
    'fleet.cta.title': 'Vehicle Reservations & Inquiries',
    'fleet.cta.description': 'We will propose the optimal vehicle according to your group size and purpose. Please feel free to contact us.',
    'fleet.cta.contact': 'Contact Us',
    'fleet.cta.quote': 'Request Quote',
    
    // Contact Page Details
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone Number',
    'contact.info.mobile': 'Mobile: 080-6588-4932 (Sawamura)',
    'contact.info.email': 'Email',
    'contact.info.address': 'Address',
    'contact.info.address.detail': '12-31 Miyako, Abiko-shi, Chiba 270-1102',
    
    // Contact Page Extended
    'contact.hours': 'Business Hours',
    'contact.hours.detail': 'Weekdays 9:00-17:00\nWeekends & Holidays by consultation',
    'contact.sns': 'Social Media',
    'contact.form.title': 'Contact Form',
    'contact.form.type.general': 'General Inquiry',
    'contact.form.type.group': 'Group Booking',
    'contact.form.type.corporate': 'Corporate Service',
    'contact.form.date': 'Planned Date',
    'contact.form.participants': 'Number of Participants',
    'contact.form.destination': 'Destination/Route',
    'contact.form.destination.placeholder': 'e.g.: Narita Airport → Tokyo Skytree → Hotel',
    'contact.form.placeholder.general': 'Please let us know your questions or requests',
    'contact.form.placeholder.group': 'Please let us know your purpose, detailed schedule, special requests, etc.',
    'contact.form.placeholder.corporate': 'Please let us know your corporate service inquiries',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Thank you for your inquiry. We will reply within 2 business days.',
    'contact.form.error': 'Sorry, submission failed. Please try again later.',
    'contact.emergency.title': 'Emergency / Urgent Contact',
    'contact.emergency.description': 'For same-day emergency contact or urgent consultation, please call directly.',
    'contact.emergency.call': 'Call 080-6588-4932 (Sawamura)',
    
    // Safety Page
    'safety.description': 'We prioritize customer safety and security above all else, implementing thorough safety management.',
    'safety.policy.title': 'Safety Policy',
    'safety.policy.subtitle': 'We achieve safe transportation based on the following policies',
    'safety.policy.management.title': 'Management Policy',
    'safety.policy.management.desc': 'Position transportation safety as the foundation of our business, establishing clear goals and plans.',
    'safety.policy.priority.title': 'Safety First',
    'safety.policy.priority.desc': 'All employees thoroughly practice "human life priority, safety first".',
    'safety.policy.compliance.title': 'Regulatory Compliance',
    'safety.policy.compliance.desc': 'Balance traffic law compliance with environmental protection, continuously improving.',
    'safety.policy.disclosure.title': 'Information Disclosure',
    'safety.policy.disclosure.desc': 'Actively disclose safety-related information internally and externally.',
    
    'safety.measures.title': 'Specific Safety Measures',
    'safety.measures.subtitle': 'Ensuring safety from three aspects: vehicles, personnel, and systems',
    'safety.measures.vehicle.title': 'Vehicle Safety Equipment',
    'safety.measures.vehicle.abs': 'ABS (Anti-lock Brake System)',
    'safety.measures.vehicle.airbag': 'Airbag System',
    'safety.measures.vehicle.seatbelt': 'Seatbelts (All Seats)',
    'safety.measures.vehicle.camera': 'Backup Camera & Drive Recorder',
    'safety.measures.vehicle.emergency': 'Emergency Exits & Lights',
    'safety.measures.vehicle.safety': 'Fire Extinguisher & First Aid Kit',
    'safety.measures.training.title': 'Driver Education',
    'safety.measures.training.orientation': 'New Employee Safety Training',
    'safety.measures.training.regular': 'Regular Safety Seminars',
    'safety.measures.training.prediction': 'Risk Prediction Training',
    'safety.measures.training.health': 'Health Management Guidance',
    'safety.measures.training.aptitude': 'Aptitude Test Participation',
    'safety.measures.training.eco': 'Eco-Driving Training',
    'safety.measures.maintenance.title': 'Vehicle Inspection & Maintenance',
    'safety.measures.maintenance.daily': 'Daily Inspection (Before/After Operation)',
    'safety.measures.maintenance.regular': 'Periodic Inspection (Legal Inspection)',
    'safety.measures.maintenance.cleaning': 'Vehicle Cleaning & Disinfection',
    'safety.measures.maintenance.parts': 'Tire & Brake Inspection',
    'safety.measures.maintenance.record': 'Maintenance Record Management',
    'safety.measures.maintenance.response': 'Immediate Response to Malfunctions',
    
    'safety.training.title': 'Driver Training System',
    'safety.training.description1': 'We implement systematic training programs for all drivers, from orientation training to continuous safety education.',
    'safety.training.description2': 'We provide comprehensive education not only for improving safe driving techniques but also for customer service manners and emergency response to ensure customers can use our services with confidence.',
    'safety.training.orientation.title': 'Orientation Training',
    'safety.training.orientation.desc': '40-hour intensive training',
    'safety.training.regular.title': 'Regular Training',
    'safety.training.regular.desc': 'Monthly safety seminars',
    'safety.training.aptitude.title': 'Aptitude Test',
    'safety.training.aptitude.desc': 'Annual mandatory participation',
    'safety.training.health.title': 'Health Management',
    'safety.training.health.desc': 'Regular health checkups',
    'safety.training.image.alt': 'Driver Training',
    
    'safety.covid.title': 'Infection Control Measures',
    'safety.covid.subtitle': 'Thorough COVID-19 infection control measures ensure safe and secure use',
    'safety.covid.vehicle.title': 'Vehicle Infection Control',
    'safety.covid.vehicle.disinfection': 'Vehicle interior disinfection before/after operation',
    'safety.covid.vehicle.cleaning': 'Cleaning seats, handrails, etc.',
    'safety.covid.vehicle.ventilation': 'Utilization of ventilation system',
    'safety.covid.vehicle.capacity': 'Passenger capacity adjustment',
    'safety.covid.vehicle.spacing': 'Ensuring seat spacing',
    'safety.covid.staff.title': 'Staff Health Management',
    'safety.covid.staff.temperature': 'Daily temperature measurement',
    'safety.covid.staff.mask': 'Thorough mask wearing',
    'safety.covid.staff.sanitizer': 'Hand sanitization implementation',
    'safety.covid.staff.absence': 'Work prohibition when feeling unwell',
    'safety.covid.staff.testing': 'Regular PCR testing',
    'safety.covid.customer.title': 'Customer Requests',
    'safety.covid.customer.mask': 'Please wear masks',
    'safety.covid.customer.sanitizer': 'Please cooperate with hand sanitization',
    'safety.covid.customer.health': 'Please consult if feeling unwell',
    'safety.covid.customer.seating': 'Please cooperate with seat assignment',
    'safety.covid.customer.conversation': 'Please keep conversations in the vehicle to a minimum',
    
    'safety.emergency.title': 'Emergency Contact',
    'safety.emergency.description': 'If you notice any abnormalities during operation, please contact us immediately.',
    'safety.emergency.contact': 'Emergency Contact: 080-6588-4932',
    'safety.emergency.police': 'Police: 110',
    
    'safety.record.title': 'Safety Record',
    'safety.record.accidents.number': '0 Cases',
    'safety.record.accidents.label': 'Serious Accidents',
    'safety.record.accidents.period': '(2019 - Present)',
    'safety.record.inspection.number': '100%',
    'safety.record.inspection.label': 'Legal Inspection Rate',
    'safety.record.inspection.period': '(Annual)',
    'safety.record.training.number': 'Monthly',
    'safety.record.training.label': 'Safety Training',
    'safety.record.training.period': '(All Drivers)',
    
    // FAQ Page
    'faq.description': 'Frequently asked questions compiled concisely. If you cannot find the information you are looking for, please feel free to contact us.',
    'faq.search.placeholder': 'Search by keyword...',
    
    // FAQ Categories
    'faq.category.all': 'All',
    'faq.category.booking': 'Booking',
    'faq.category.pricing': 'Pricing',
    'faq.category.safety': 'Safety',
    'faq.category.service': 'Service',
    'faq.category.vehicle': 'Vehicle',
    'faq.category.other': 'Other',
    
    // FAQ Questions & Answers
    'faq.q1': 'How far in advance should I make a reservation?',
    'faq.a1': 'Please make your reservation at least 3 days before your desired date of use. However, during busy periods (Golden Week, Obon, year-end and New Year holidays, etc.), we recommend booking at least one week in advance. For urgent requests, please contact us directly by phone.',
    'faq.q2': 'Can I cancel my booking?',
    'faq.a2': 'Yes, cancellation is possible. However, cancellation fees may apply. Up to 7 days before: Free, 3-6 days before: 30% of fare, Previous day/Same day: 100% of fare. Please refer to our transport terms for details.',
    'faq.q3': 'How are the fares determined?',
    'faq.a3': 'Basic fares are determined by vehicle size, usage time, and travel distance. There are variations for weekdays/weekends/holidays and seasons. Estimates are free, so please feel free to contact us.',
    'faq.q4': 'Are there any additional charges?',
    'faq.a4': 'Additional charges not included in the basic fare include highway tolls, parking fees, and driver accommodation fees for overnight trips. These can be confirmed in advance with your estimate.',
    'faq.q5': 'What safety measures are in place for drivers?',
    'faq.a5': 'We conduct regular safety training, aptitude assessments, and health management for all drivers. We also thoroughly check driver condition and conduct alcohol tests before operation, emphasizing safe driving.',
    'faq.q6': 'What safety equipment do the vehicles have?',
    'faq.a6': 'All vehicles are equipped with ABS, airbags, drive recorders, and backup cameras. We also conduct regular inspections and maintenance beyond legal standards to ensure safety.',
    'faq.q7': 'Is English language support available?',
    'faq.a7': 'Yes, it is available. We provide bilingual support in Japanese and English, so overseas customers can use our services with confidence. We also offer tourist guidance and interpretation services.',
    'faq.q8': 'Can you propose tourism plans?',
    'faq.a8': 'Yes, we can. We propose optimal tourism routes according to customer preferences and budget. We can also arrange accommodation and tourist facility tickets.',
    'faq.q9': 'How many passengers can ride?',
    'faq.a9': 'Mid-size bus: 27 passengers, Microbus (Coaster): 23 passengers (18 regular + 5 auxiliary), Microbus (Rosa): 24 passengers (19 regular + 5 auxiliary). Please see our fleet page for details.',
    'faq.q10': 'How much luggage can be loaded?',
    'faq.a10': 'Each vehicle has trunk space. The mid-size bus has dual large-capacity trunks, and the Microbus (Rosa) is equipped with a large trunk, so suitcases and large luggage are safe.',
    'faq.q11': 'Is pickup and drop-off possible at places other than Narita Airport?',
    'faq.a11': 'Yes, it is possible. We provide pickup and drop-off services at Haneda Airport, various stations, hotels, and other desired locations. The Kanto region is our basic area, but we also accommodate requests for Tohoku and Kansai regions.',
    'faq.q12': 'What infection control measures are in place?',
    'faq.a12': 'We implement COVID-19 infection control measures including vehicle disinfection and cleaning, thorough ventilation, driver health management, and mask wearing. Please see our safety commitment page for details.',
    
    // FAQ UI Elements
    'faq.no.results': 'No matching questions found.',
    'faq.reset.search': 'Reset search criteria',
    'faq.contact.title': 'Cannot find the information you are looking for?',
    'faq.contact.description': 'Please feel free to contact us. Our professional staff will answer you carefully.',
    'faq.contact.phone.title': 'Phone Inquiry',
    'faq.contact.phone.hours': 'Weekdays 9:00-17:00\nWeekends & Holidays by consultation',
    'faq.contact.email.title': 'Email Inquiry',
    'faq.contact.email.hours': 'Reply within 2 business days\nAccepted 24 hours',
    'faq.contact.form': 'Contact Form',
    'faq.popular.title': 'Popular Questions',
    'faq.view.details': 'View Details',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ja');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ja' ? 'en' : 'ja');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
